import express from "express";
import cors from "cors";
import helmet from "helmet";
import morgan from "morgan";
import swaggerUi from "swagger-ui-express";
import { swaggerSpec } from "./config/swagger.js";
import serviceRoutes from "./routes/service.routes.js";
import { errorHandler, notFoundHandler } from "./middlewares/error.middleware.js";
const app = express();
const corsOrigin = process.env.CORS_ORIGIN?.trim();
app.use(cors(corsOrigin ? { origin: corsOrigin } : undefined));
app.use(helmet());
app.use(morgan(process.env.NODE_ENV === "production" ? "combined" : "dev"));
app.use(express.json());
app.use("/api/docs", swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.get("/health", (_req, res) => res.json({ ok: true, app: "Fixly API" }));
app.use("/api/services", serviceRoutes);
app.use(notFoundHandler);
app.use(errorHandler);
export default app;
